# Generated by Django 4.1.2 on 2022-12-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images",
                        verbose_name="프로필 사진",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=255, null=True)),
                ("login_type", models.CharField(default="", max_length=10, null=True)),
            ],
            options={"db_table": "users",},
        ),
    ]
