# Generated by Django 4.0.6 on 2022-11-03 01:42

import Post.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='카테고리 명')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_title', models.CharField(max_length=100, verbose_name='질문 제목')),
                ('Question_content', models.TextField(verbose_name='질문 내용')),
                ('Question_image', models.ImageField(blank=True, null=True, upload_to=Post.models.question_image_rename, verbose_name='질문 사진')),
                ('Question_created_at', models.DateTimeField(auto_now_add=True, verbose_name='질문 날짜')),
                ('Question_counting', models.IntegerField(default=0, null=True, verbose_name='질문 조회수')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('Question_category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='카테고리1', to='Post.category')),
                ('Question_category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='카테고리2', to='Post.category')),
                ('Question_category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='카테고리3', to='Post.category')),
                ('Question_category4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='카테고리4', to='Post.category')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_title', models.CharField(max_length=100, verbose_name='답변 제목')),
                ('Answer_content', models.TextField(verbose_name='답변 내용')),
                ('Answer_image', models.ImageField(blank=True, null=True, upload_to=Post.models.answer_image_rename, verbose_name='답변 사진')),
                ('Answer_created_at', models.DateTimeField(auto_now_add=True, verbose_name='답변 날짜')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Post.question')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
