# Generated by Django 4.1.2 on 2023-01-05 19:05

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Answer_title",
                    models.CharField(max_length=100, verbose_name="답변 제목"),
                ),
                ("Answer_content", models.TextField(verbose_name="답변 내용")),
                (
                    "Answer_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Post.models.answer_image_rename,
                        verbose_name="답변 사진",
                    ),
                ),
                (
                    "Answer_created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="답변 날짜"),
                ),
            ],
            options={"db_table": "Answers",},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=20, verbose_name="카테고리 명"),
                ),
            ],
            options={"db_table": "Categories",},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Question_title",
                    models.CharField(max_length=100, verbose_name="질문 제목"),
                ),
                ("Question_content", models.TextField(verbose_name="질문 내용")),
                (
                    "Question_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Post.models.question_image_rename,
                        verbose_name="질문 사진",
                    ),
                ),
                (
                    "Question_created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="질문 날짜"),
                ),
                (
                    "Question_counting",
                    models.IntegerField(default=0, null=True, verbose_name="질문 조회수"),
                ),
            ],
            options={"db_table": "Questions",},
        ),
    ]
